version: "3.2"
services:
 zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

 kafka:
    build: .
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
 prometheus:
   image: prom/prometheus
   ports:
     - "9090:9090/tcp"
   volumes:
     - ./mount/prometheus:/etc/prometheus
   links:
     - kafka

 grafana:
   depends_on:
    - prometheus
   image: grafana/grafana-oss
   ports:
     - "3000:3000"
 
 kafdrop:
   image: obsidiandynamics/kafdrop:latest
   depends_on:
     - kafka
   ports:
     - 19000:9000
   environment:
     KAFKA_BROKERCONNECT: kafka:9092